---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-k
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux-resources
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-r
  targetNamespace: flux-system
  timeout: 3m0s
  wait: true


