apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-all-permissions
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-all-permissions
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
roleRef:
  kind: ClusterRole
  name: flux-all-permissions
  apiGroup: rbac.authorization.k8s.io
