apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-permissions
  namespace: flux-system
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-permissions-binding
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
roleRef:
  kind: Role
  name: flux-permissions
  apiGroup: rbac.authorization.k8s.io
